### ISSUE TITLE
[Bug]: I get ALL the time that i ride the saddle

### ISSUE THREAD

**Issue by lonVic** [AlaharranHonor/SWEquestrianM#121]
### What happened?

Hey SWEM OWNERS! 
Im i player of SWEM and i have a bug and its that when i ride my horse i get the saddle of the horse ALL the time....
IDK if anyone happend or no but please read this report and contact to me 
THANKS U!

### What should happen?

I wanted horse to go zoom instead.

### Mods

SWEM
SWLM
GEKOLIB
and the player

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Closing as stale. If commented, feel free to reopen. @lonVic
