### ISSUE TITLE
[Bug]: swem-server.toml doesn't work properly

### ISSUE THREAD

**Issue by monobanana1** [AlaharranHonor/SWEquestrianM#123]
### What happened?

I disabled the swem ores in the serverconfig and they still appear in new chunks.

### What should happen?

*

### Mods

*

### SWEM Version

swem-1.16.5-0.5.1.0

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
*
```

**Comment by monobanana1** [comment]
Sorry for the late reply.

Yes, I have tried that method and the problem still persists.
I have the latest version of forge installed, I don't know if that has anything to do with it.

**Comment by MagnusHJensen** [comment]
What swem ores are you disabling?

Also ensure the value is actually set to the wanted one.

If it's the Star Worm Cobble, remember that SWLM also generates that ore.

**Comment by monobanana1** [comment]
Amethys, Cantazarite and SWEMCobble.

![image_2022-10-02_163103148](https://user-images.githubusercontent.com/114214490/193459487-35528a5b-3817-45d8-99ae-dd2674be526d.png)

Setting them to "false" doesn't work, so I tried setting BottomHeight to 0 and they no longer appear in new chunks.

**Comment by MagnusHJensen** [comment]
https://wiki.swequestrian.com/books/star-worm-equestrian-mod/page/common-config

Ore generation config has moved places, so this is the new place you will find it, and being respected.
