### ISSUE TITLE
[Bug]: Horse slowly moves forward while tied 

### ISSUE THREAD

**Issue by Helplesss13** [AlaharranHonor/SWEquestrianM#126]
### What happened?

Hello! 

I have noticed that when using the swem provided hitching posts that all of my swem horses slowly creep forward (without moving legs) when tied! Both cross tied and regular One tied! 

### What should happen?

I don’t think the horse is supposed to slowly creep forward while tied up.. 

### Mods

SWEM
SWDM
SWLM
Macaws Fences 
MrCrayfish’s Vehicle Mod

### SWEM Version

V1

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by Mothfet** [comment]
not a bug. this is unfortunately vanilla lead behaviour; not something swem-related.
