### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lil10102** [AlaharranHonor/SWEquestrianM#147]
### What happened?

Horses don’t move in paddok

### What should happen?

I want my horses to move more often in the paddok but they don’t 

### Mods

SWEM-1.16.5
SWDM-1.16.5
SWLM-1.16.5
Playeranimator-1.16.5
Better Third Person-1.16.5
GeckoLib-1.16.5

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
More movement and more visible behavior is planned.
