### ISSUE TITLE
[Bug]: i installed the mod, and could not place/use any items

### ISSUE THREAD

**Issue by txhChelly** [AlaharranHonor/SWEquestrianM#153]
### What happened?

i downloaded everything i needed to download, on none of my servers does the mod work, but in singleplayer it does.

### What should happen?

it should work on my server

### Mods

GECKOLIB 3.0.92+ & PLAYERANIMATOR 0.3.5+1.16.5

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
I can't reproduce this, nor heard of anyone having the same issues.
