### ISSUE TITLE
[Bug]: Swem crashes minecraft before it opens

### ISSUE THREAD

**Issue by Trodor7** [AlaharranHonor/SWEquestrianM#164]
### What happened?

I've even tried allocating 5GB of RAM, but it doesn't even open?  I've even deleted and remade the installation, I spoke to an admin, but they told me they didn't know any solutions other than the ones we tried. I'm really hoping there's a way to fix this, bc I absolutely LOVE this mod, but can't play
![image](https://user-images.githubusercontent.com/114105248/191586267-802c07e4-609c-4100-af6c-de210fea1b0e.png)

### What should happen?

Minecraft should open, I think?

### Mods

Swem - 1.16.5
Geckolib - 1.16.5
Player Animation Lib - 1.16.5
![image](https://user-images.githubusercontent.com/114105248/191585913-6cb77b44-6580-46e1-bece-5dd93dec13c4.png)

### SWEM Version

V1

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [ ] Multiplayer
- [X] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
I couldn't figure out how to attach the .log file, so I put it in paste bin! I really hope this helps, can't wait to play SWEM if the bug can be fixed!

https://pastebin.com/uNcZaCrV
```

**Comment by MagnusHJensen** [comment]
This is nothing with SWEM, your configs are corrupted.

Please go ahead and delete the entire config folder here: `AppData\Roaming\.minecraft`
