### ISSUE TITLE
[Bug]: Crash when horseData.json has invalid JSON

### ISSUE THREAD

**Issue by V4L0R0US** [AlaharranHonor/SWEquestrianM#460]
### What happened?

When I try to load my world with swem it crashes with an exit code of -1. It works perfectly fine with my other mods, so I'm sure swem and geckolib are the issues. I have tried updating my optifine (which didn't matter anyways because the game still crashed after removing optifine) as well as backdating my forge to the recommended version and switching to the latest version.

### What should happen?

My world should load without crashing.

### Mods

swem-1.16.5-0.5.2.0
player-animator-lib-forge-0.4.0test1+1.16.5
geckolib-forge-1.16.5-3.0.92

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [x] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
Latest log:
See lines 1013 - 2114
https://paste.gg/p/kd_licious/e951f8dd143a4889954503d7da17e2a7

Crash report: 
https://paste.gg/p/kd_licious/b455ec62d3954d789e8881552408ca52
```

**Comment by MagnusHJensen** [comment]
This is due to a corrupted horse data file.

You can navigate to world/server folder -> serverconfig -> swem -> Then delete the `horseData.json` file.
**This will make you loose tracking, if any was made.**
A fix is coming in the next release.
