### ISSUE TITLE
[Bug]: cannot equip armor and more variants and the horse cannot drink or anything like that

### ISSUE THREAD

**Issue by gabbigamers** [AlaharranHonor/SWEquestrianM#464]
### What happened?

so basically i installed the latest version with everything that is required but then i i tried to ride the horse took a while for it to let me tame it and the i couldnt give it any kinds of armor pieces and it wouldnt drink nor poop or piss or eat.

### What should happen?

i wanted the horse to do all of the things that was listed in the issue

### Mods

SWEM - 1.16.5-0.5.2.0

geckolib-forge-1.16.5-3.0.92.jar

player-animation-lib-forge-0.4.0-test1+1.16.5

bendy-lib-forge-1.2.1.jar

waifucraft_1.16.5_1.7.1.jar

iceandfire-2.1.11-1.16.5.jar

gunsrpg-1.16.5-1.0.5.144.jar

configuration-1.16.5-1.2.5.jar

citadel-1.8.1-1.16.5.jar

### SWEM Version

1.16.5-0.5.2.0

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
*https://pastebin.com/2uapJ7sx*
```

**Comment by MagnusHJensen** [comment]
Logs don't provide anything except you are missing citadel.

To equip armor, you need the adventure tack! ([Be sure to look at our wiki](https://wiki.swequestrian.com))

The food/water is currently being re-worked.

The poop/pee is on a timed basis, did you wait in-game days?
