### ISSUE TITLE
[Bug]: Not letting me go up a gait

### ISSUE THREAD

**Issue by Harleyeq** [AlaharranHonor/SWEquestrianM#468]
### What happened?

Every time click "G" my horse will not go up a gait.

### What should happen?

After I click "G" my horse should trot, canter, ect.

### Mods

Swem, Swdm, Swlm, Worldedit all 1.16.5

### SWEM Version

16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by SugarJulia** [comment]
You're supposed to press H for the horse to go up a gait, G slows them down

**Comment by dronade** [comment]
See SugarJulia's comment.
