### ISSUE TITLE
[Bug]: Tack on Blankets

### ISSUE THREAD

**Issue by ShyWoolf** [AlaharranHonor/SWEquestrianM#478]
### What happened?

When you equip all your normal tack to your horse, you can put a blanket on and still have the tack on, allowing you to ride with a blanket. When you take off the blanket, you have access to change your tack, as if the blanket was ever on. Not sure if this was intentional or not.
![2022-10-07_11 38 40](https://user-images.githubusercontent.com/93551814/194604734-f2ea23ca-ea1d-48ed-a353-4dc7e90b8cc1.png)

### What should happen?

Blankets should either disable and unrender tack when on, or the tack should pop off?

### Mods

![Ghosty Mod List](https://user-images.githubusercontent.com/93551814/194603089-04a2b344-2e9a-4337-87bd-c02eaa345c9e.png)

### SWEM Version

swem-1.16.5-0.5.2.0

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
How did you manage to put on the blanket? I can't seem to do it.

**Comment by ShyWoolf** [comment]
> How did you manage to put on the blanket? I can't seem to do it.

Sorry for the MASSIVE delay on my part, after equiping the full adventure tack, you can equip the blanket as if it is horse armour, without the tack itself unrendering or disabling.

**Comment by MagnusHJensen** [comment]
Thank you for getting back.

This is now fixed.
