### ISSUE TITLE
[Bug]: None of my horses graze , lay down, eat, or drink.

### ISSUE THREAD

**Issue by batcite777** [AlaharranHonor/SWEquestrianM#486]
### What happened?

I've noticed that none of my horses graze when they're in a field or even lay down. They don't drink or eat either, only while being hand fed but not by themselves.

### What should happen?

They should be able to drink and eat. 

### Mods

- GeckoLib
- playerAnimator
- SWEM

### SWEM Version

1.16.5, phase one

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Mac

**Comment by vividlyindigo** [comment]
"Other idle animations such as grazing and laying down are accessible only via RRP commands at this time"

Horses will not preform these animations on their own in V1 _as stated in the wiki_, this is not a bug <3

**Comment by dronade** [comment]
As said by Indigo, grazing/laying down is only available via commands.
For eating/drinking, that system is currently broken and has already been reported.
