### ISSUE TITLE
[Bug]: Error Enchantment Message for other Mods.

### ISSUE THREAD

**Issue by EliandraAlveran** [AlaharranHonor/SWEquestrianM#497]
Im realy confused. 
After patching Swems Echantment Update my Game have some errors.

After loggin in the game.. The Chat tell me this (Pictures):

The confusing Thing. I dont have any other Mod then Swem and Crafting Tweakers running...
But here he is telling me 2 Errors for non installed Mods..

- Modular Machinery 
- Living enchantment

![Chat1](https://user-images.githubusercontent.com/115932318/196046585-cf655abd-9019-46f6-bcb5-7aeebdcdfc92.png)
![chat2](https://user-images.githubusercontent.com/115932318/196046590-01f96095-f374-41eb-a84d-b1e0eb982658.png)

### What should happen?

NO Error for Mods that dont exsist on my server.

### Mods

Swem
Player Animation
geko
Forge
Crafting Tweakers

### SWEM Version

1.16.5-0.5.3.0

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Nothing we can help you with sorry.
Either open an issue on CraftTweaker or the respective mods.

You could also provide the logs from your game.

**Comment by EliandraAlveran** [comment]
They will tell the same. Cause there Mod run also very fine without SWEM. 

Normaly i wouldnt set this in but Crafting Tweakers is a very important Mod for Modpacks. 
You cant realy run without this. 
But maybe its important to know that there is a incompatibility issue
