### ISSUE TITLE
[Bug]: render command not working

### ISSUE THREAD

**Issue by bunnybunzzy** [AlaharranHonor/SWEquestrianM#500]
### What happened?

After using /wild i wanted to render in the tack again and then found the render command did not exist, i reported this in the discord server.

### What should happen?

Tack should be rendered back in

### Mods

Swem, swdm

### SWEM Version

Most recent

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by vividlyindigo** [comment]
/swem render is an OP command, is it possible you are not Oped on your server?:) Regardless, logging out and logging back in will return your tack to you

**Comment by MagnusHJensen** [comment]
You most likely do not have permission for it.
