### ISSUE TITLE
[Bug]: Items not presenting correctly

### ISSUE THREAD

**Issue by n0rthing** [AlaharranHonor/SWEquestrianM#502]
### What happened?

I've been told to report this as a bug. A few friends on our Aternos server are having issues with some blocks and such while others of us are seeing things as we should, a few broken items are;
- Bridle racks are showing as water
- Gates of any kind aren't placing as they should, they are indecisive on where to face
- Seperators are showing as feeders
These are only some out of few blocks we have used. I'll supply screenshots below. 

![image](https://user-images.githubusercontent.com/116468421/197366726-4730e0cc-2ca2-4c78-af87-5fc326af87e9.png)
![image](https://user-images.githubusercontent.com/116468421/197366733-cf4ff97d-ec76-4ae7-9cca-2b4a2f01dec9.png)
![image](https://user-images.githubusercontent.com/116468421/197366739-f446dfdd-f4c0-4ad0-92d3-bbe550b70cb7.png)
![image](https://user-images.githubusercontent.com/116468421/197366745-4dbb4b46-1911-4852-a902-6c7162342666.png)

**BACK INFO**
We did have issues with another of our Aternos server (We had the very same mods and versions installed as we do now) but that was a problem with fairy lights causing too much lag and making the server unusable as it wouldn't allow anyone on. This is now the second server we have tried but have only experienced this issue now, I thought it best to add about the previous Aternos server incase it had any relevance. Some things we have tried doing are:
- Restarting the server
- Using later versions of SWEM
- Replacing the items once doing the above

### What should happen?

Items should be being placed as shown in creative inventory. Gates should be facing one way and matching up.

### Mods

![bandicam 2022-10-23 01-07-51-349](https://user-images.githubusercontent.com/116468421/197366945-381a14e5-46ba-4a7f-ae1a-1367bf749349.jpg)

### SWEM Version

swem-1.16.5-0.5.2.12

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [x] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by n0rthing** [comment]
I'm writing this on behalf of a friend as they can struggle with communication. Having looked back on the photos the fences are also not facing how they should.

**Comment by MagnusHJensen** [comment]
Assuming this is due to a problem with invalid tileentities we had.
Please try a newer version and report back if it still happens.
