### ISSUE TITLE
[Bug]: Redstone and Lapis isnt working

### ISSUE THREAD

**Issue by Sebijax** [AlaharranHonor/SWEquestrianM#503]
### What happened?

When using lapis and Redstone on a tamed SWEM horse, it doesn't work to go through the coat cycle, only mounts the horse.

### What should happen?

Just wishing to go through the cycle

### Mods

GeckoLib 1.16.5-3.0.94.jar
PlayerAnimator lib forge-0.3.5+1.16.5.jar
Star Worm Decor Mod 1.16.5-2.0.2.jar
Star Worm Lighting Mod 1.16.5-1.1.4.jar

### SWEM Version

1.16.5-0.5.2.12.jar

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Please attach a video showcasing this.

**Comment by Sebijax** [comment]
> Please attach a video showcasing this.

Heyy! I actually figured it out! I was using the incorrect block, however was directed here, sorry for the mix up and thank you!
