### ISSUE TITLE
[Bug]: Singleplayer world crashing after attempting to tame horse.

### ISSUE THREAD

**Issue by miwakokiss** [AlaharranHonor/SWEquestrianM#505]
### What happened?

I joined the game, spawned a SWEM horse then right clicked in order to tame it. Game crashed instead and it kept happening every single time, so I was unable to tame the horse.

### What should happen?

The goal was to be able to tame the horse after right clicking several times.

### Mods

![image](https://user-images.githubusercontent.com/116676082/197856695-e696edc2-d28c-4b2a-b4ec-501ab0e2d172.png)

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
https://paste.gg/p/anonymous/dca6d52556ea4aba9738b2bcb08cf5e9
```

**Comment by MagnusHJensen** [comment]
Downgrade geckolib to version 3.0.96.
