### ISSUE TITLE
[Bug]: Game Crash, Rendering entity in world | Version 0.5.3.1

### ISSUE THREAD

**Issue by Cactus-Kat** [AlaharranHonor/SWEquestrianM#508]
### What happened?

When logging on the server and having downloaded all the correct mods listed in the mods manifest, all the horses go into a T-Pose then a crash follows when trying to ride. Via Vanilla MC Launcher.

(Crash Report)
[crash-2022-10-26_20.19.14-client.txt](https://github.com/AlaharranHonor/SWEquestrianM/files/9874684/crash-2022-10-26_20.19.14-client.txt)

### What should happen?

The game should not crash and the animations should work properly.

### Mods

(Modlist)
![modlist](https://user-images.githubusercontent.com/116772321/198164120-c2fd0acd-3f49-4d8e-853c-9d182abd98fa.PNG)

### SWEM Version

0.5.3.1

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Fixed with version: `0.5.3.22`
