### ISSUE TITLE
[Bug]: Server crashes whenever a player attempts to ride their SWEM horses

### ISSUE THREAD

**Issue by ghost** [AlaharranHonor/SWEquestrianM#510]
### What happened?

When a player attempt to ride a SWEM horse, all of the players get timed out and server requires a restart.

Mod and server worked fine until the last couple of days. Problem occurred suddenly without any server changes. Tried updating to the latest SWEM release and geckolib but issue still persists.

### What should happen?

Players should be able to ride their horses without causing issues

### Mods

![modlist](https://user-images.githubusercontent.com/116924297/198843909-4593f1aa-c039-4131-8892-2d1f42643ae0.png)

### SWEM Version

0.5.3.1 and 0.5.2.12

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Linux

### Relevant log output

```shell
crash report: https://pastebin.com/edRmiXjg

Debug profile: https://pastebin.com/fUudVeMB
```

**Comment by MagnusHJensen** [comment]
We don't support hybrids. So my advice is to not use archlight, also since you are allowed to use an incompatible java version with the MC version.
