### ISSUE TITLE
SWEM vs. SWLM Star Worm Goop

### ISSUE THREAD

**Issue by CircusSeal** [AlaharranHonor/SWEquestrianM#513]
I'm trying to make SW Spruce Wood Planks, but I can't do it with the SW goop from SWEM, only the SW goop from SWLM. However, when I try to make the goop from SWLM, it keeps insisting on making the one from SWEM. I even made both versions of mortar and pestle, but it still doesn't work.

I have Polymorph, which for some reason, allowed me to correct the conflict once, but when I tried again, it didn't.

**Comment by Mothfet** [comment]
What versions are you running?

**Comment by CircusSeal** [comment]
> What versions are you running?

swdm-1.16.5-2.0.2

swem-1.16.5-0.5.2.7

swlm-1.16.5-1.1.4

**Comment by Mothfet** [comment]
> > What versions are you running?
> 
> 
> 
> swdm-1.16.5-2.0.2
> 
> 
> 
> swem-1.16.5-0.5.2.7
> 
> 
> 
> swlm-1.16.5-1.1.4

Thank you! Consider updating to SWEM 5.3.3; it will not fix this specific recipe issue, but it may fix others. I've added this conflict to SWLM's fix list as it's technically a SWLM bug and not a SWEM one. Issue will be closed when the fix is pushed!

**Comment by CircusSeal** [comment]
> > > What versions are you running?
> > 
> > 
> > swdm-1.16.5-2.0.2
> > swem-1.16.5-0.5.2.7
> > swlm-1.16.5-1.1.4
> 
> Thank you! Consider updating to SWEM 5.3.3; it will not fix this specific recipe issue, but it may fix others. I've added this conflict to SWLM's fix list as it's technically a SWLM bug and not a SWEM one. Issue will be closed when the fix is pushed!

Oh, has SWEM updated since? Awesome! I totally will! :D Thank you!
