### ISSUE TITLE
[Bug]: konie nie jedzą i nie piją , nie są głodne 

### ISSUE THREAD

**Issue by paulix420** [AlaharranHonor/SWEquestrianM#526]
### What happened?

A bug happened!

### What should happen?

I wanted horse to go zoom instead.

### Mods

Forge 

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by XDelphix** [comment]
@paulix420 Please note bug reports need to be in English.

Additionally, horses not experiencing hunger/thirst or eating/drinking has been reported already and is a known issue. If you would like to add any information you can add it to the existing post:
https://github.com/AlaharranHonor/SWEquestrianM/issues/151
