### ISSUE TITLE
[Bug]: Game Crash + File issue

### ISSUE THREAD

**Issue by Naturegirl555** [AlaharranHonor/SWEquestrianM#527]
### What happened?

On 12/2, I was playing my world. My world was really laggy and I had 8 mods running in the world (SWEM, SWLM, Geckolib, Playeranimator, and a few others) It has always been laggy but recently, the game would crash whenever I would try to ride my horses. I took off the mod that I knew was causing the lag so it would lessen and hopefully fix the riding issue. The game still crashed when I right clicked on my horse, though, so I deleted everything, hoping to redownload it in hopes it would fix any issues. As I was downloading SWEM and the two mods that needed to go with it (Geckolib and Playeranimator) the file would say "Virus scan failed". I panicked and deleted the files again. Then I tried redownloading them a second time, and again they failed the virus scan so I couldn't play SWEM anymore. Any ideas on how to fix this? Because the game was crashing, I was starting to think that there was a virus in the file but wasn't sure how it got there as when I first downloaded everything, it all worked. Not sure what happened but if you have any ideas on fixing it, I'd like to try it.

### What should happen?

I need to ride my horse without the game crashing and have the files not have viruses in them.

### Mods

Star Warm Equestrian Mod, Star Worm Lighting Mod, Geckolib, Playeranimator, Doggy Talents Mod, Biomes o' Plenty, Mr. Crayfish Furniture Mod, and Fairy Lighting.

### SWEM Version

SWEM - 1.16.5-0.5.3.3 / Main File

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by Naturegirl555** [comment]
Most everything is fixed! I've gotten most of the files to work (Still having some trouble with SWLM) and now it says "Missing License Information".. Not sure what that means.

**Comment by XDelphix** [comment]
Hi @Naturegirl555,

SWEM and it's downloads do not contain viruses (and are carefully checked when uploaded by the CurseForge team) but naturally you should be cautious in downloading any other files from unverified sources. It doesn't sound to me like your issues are specific to SWEM (though there's not a lot of info to go off), and a lot of factors can contribute to lag such as computer specs, mods and settings, use of TXP and shaders.

If you would like to provide any crash logs we would be better able to identify if the issue is related to SWEM or not.

**Comment by Naturegirl555** [comment]
Oh alright!! Thanks for responding. I’m not sure what was going on but it struggled for a minute. All good now, though. Sent from my iPhoneOn Dec 21, 2022, at 3:31 PM, Delphi ***@***.***> wrote:﻿
Hi @Naturegirl555,
SWEM and it's downloads do not contain viruses (and are carefully checked when uploaded by the CurseForge team) but naturally you should be cautious in downloading any other files from unverified sources. It doesn't sound to me like your issues are specific to SWEM (though there's not a lot of info to go off), and a lot of factors can contribute to lag such as computer specs, mods and settings, use of TXP and shaders.
If you would like to provide any crash logs we would be better able to identify if the issue is related to SWEM or not.
