### ISSUE TITLE
[Bug]: game crashes 

### ISSUE THREAD

**Issue by SilviaLmks** [AlaharranHonor/SWEquestrianM#533]
### What happened?

The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file swem-client.toml of type CLIENT for modid swem

My game crashes when rendering swem overlay, this is what it says ^^^
I run latest swem and geckolib, animator 0.3.5 1.16.5

### What should happen?

I need swem to run my multiplayer server, as far as i know im only one with that problem.

### Mods

geckolib 3.0.106
player animator 0.3.5+1.16.5
Swem 1.16.5 0.5.3.3

### SWEM Version

swem 1.16.5 5.3.3

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [ ] Multiplayer
- [X] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Often there is something else in the crash log.
So if you provide the entire crash log, we might be able to help a bit better.
This issue can be fixed by navigating to your config folder and deleting the mentioned file.
