### ISSUE TITLE
game keeps on crashimg

### ISSUE THREAD

**Issue by minecraftt12** [AlaharranHonor/SWEquestrianM#535]
### What happened?

i would load in to the game and get on my horse try and go into a trot and the game woukld feeze and crash and this has happend for the past week or two and i dont know what i should do to fix it or somthing

### What should happen?

what should of happend is i should of been able to go in to a trot without it crashing 

### Mods

  i dont know the mods sorry

### SWEM Version

16.5.1 

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
-805306369
```

**Comment by RileyCasper** [comment]
This sounds like you have the wrong version of Playeranimator mod. (As this is a popular crash)
https://www.curseforge.com/minecraft/mc-mods/playeranimator/files/3955873
Install this version of playeranimator and see if that fixes your problem.

**Comment by MagnusHJensen** [comment]
16.5.1 is not a valid swem version, please list the proper one.

**Comment by MagnusHJensen** [comment]
Closing due to no response.
