### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by uhhitsliv** [AlaharranHonor/SWEquestrianM#540]
### What happened?

every time i go to get on the horse, my game crashes and i cant do anything. i go back on to try again but it just continues to crash. i have the correct player animation dowloaded... please help!

### What should happen?

i should be able to ride when i get on and not have my game crash...

### Mods

SWEM 
SWIM
SWLM
Geko
Playeranimations
forge

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by XDelphix** [comment]
@uhhitsliv Please note that we will require more information to determine if this is a bug - or if the issue can be resolved by the player.

Required:
A minimum we need your crash report (latest.log) file. Please also let us know what versions of each mod you're using as the versions matter more than most people think and crashing issues are often not relating to SWEM so much as they are issues with the version of geckolib used.

**Comment by MagnusHJensen** [comment]
Since no logs is provided, I'm going to assume you are playing on a hybrid server, which is unsupported.
https://discord.com/channels/715626418893095012/997404105704210432/1035984586984927304
