### ISSUE TITLE
Keep destroying blocks and hitting animals without clicking left mouse button

### ISSUE THREAD

**Issue by leochan369** [AlaharranHonor/SWEquestrianM#542]
I have installed SWEM for my daughter and she is facing issue in the game.  The player in SWEM just kept destroying blocks and hitting animals, but she did not left click at all.  Looks like these actions were done automatically and that gets her very frustrated.  Is there a way to stop this issue please?  Thank you in advance.

**Comment by MagnusHJensen** [comment]
This is not an issue related to SWEM unfortunately.
We don't do any actions that would automatically left-click for people.
Perhaps a faulty mouse button or trackpad or another mod that is installed alongside SWEM.
