### ISSUE TITLE
[Bug]: SWEM crashing for aternos servers

### ISSUE THREAD

**Issue by Kraabab** [AlaharranHonor/SWEquestrianM#548]
### What happened?

When I run the SWEM mod on aternos I can:
- Spawn in a horse
- Tame a horse
- Dismount and put tack on the horse
- Mount horse again

But as soon as I do the last step the server will stop responding, only letting me walk around on the horse, no speeding up, no dismounting nothing before it'll say I've timed out. I then have to restart the server. There are also no crash reports for me to work with since the server doesn't technically crash.

### What should happen?

- spawn in a horse
- tame a horse
- dismount and put tack on the horse
- mount horse again
- not timeout

all while using aternos 

### Mods

geckolib-forge-1.16-3.0.106.jar
player-animation-lib-forge-0.4.0+1.16.5.jar
swdm-1.16.5-2.0.4.jar
swem-1.16.5-0.5.3.3.jar
swlm-1.16.5-1.1.4.jar

also happening with other versions. Noticed it when I had more mods than this but have also run tests with just these mods and it still happens.

### SWEM Version

swem-1.16.5-0.5.3.3.jar

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Please provide the `debug.log` for the server crash.

**Comment by Kraabab** [comment]
https://mclo.gs/5s5op4k

**Comment by MagnusHJensen** [comment]
Hybrid servers is not supported.
https://discord.com/channels/715626418893095012/997404105704210432/1035984586984927304
