### ISSUE TITLE
[Bug]: Horse's coat mane is bugged

### ISSUE THREAD

**Issue by ItzSagg** [AlaharranHonor/SWEquestrianM#557]
### What happened?

The horse coat named Schwoompl has a bugged mane. It's still bugged in the 1.18 version mod too.  
![2023-08-31_07 05 24](https://github.com/AlaharranHonor/SWEquestrianM/assets/143707573/a0855bd0-1781-4dae-bd59-75dcf6444848)

### What should happen?

I'd like to see the coat with its mane fixed because this bug ruins it a bit.

### Mods

[Unwind_with_JD.zip](https://github.com/AlaharranHonor/SWEquestrianM/files/12485717/Unwind_with_JD.zip)

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
What is bugged about it?

**Comment by MagnusHJensen** [comment]
Now double checked, it's a texture issue.
Since the development of the mod has been shut down (see discord), this will not be fixed.
Also playing on an outdated version of the mod (1.16.5, minecraft)
